Use util.sh, move util > lib.sh, update some function calls to use util.sh functions

diff --git a/bin/launch-server b/bin/launch-server
--- a/bin/launch-server
+++ b/bin/launch-server
@@ -1,14 +1,14 @@
 #!/bin/bash
 # Launches a new tmux session with the minecraft/pixelmon server running.
 
-source "$( dirname "$0" )/util"
+source "$( dirname "$0" )/lib.sh"
 
-is_server_running && print_err "Server is already running."
+is_server_running && err "Server is already running."
 
 print_date
-print_log "STARTING SERVER"
+msg "STARTING SERVER"
 
-[ -f "${SERVER_JAR}" ] || print_err "Missing server jar file: ${SERVER_JAR}"
+[ -f "${SERVER_JAR}" ] || err "Missing server jar file: ${SERVER_JAR}"
 
 cmd="java ${JAVA_ARGS} -jar \"${SERVER_JAR}\" nogui"
 if ! out="$( 2>&1      \
@@ -19,5 +19,5 @@ if ! out="$( 2>&1      \
     -n "$TMUX_WINDOW"  \
     "$cmd"             \
   )"; then
-  print_err "$out"
+  err "$out"
 fi
